CREATE DATABASE pizza_hut;
use pizza_hut;

CREATE TABLE ORDERS_DETAILS(
order_details_id INT PRIMARY KEY,
order_id INT NOT NULL,
pizza_id VARCHAR(60),
quantity INT NOT NULL
);


-- BASIC LEVEL QUESTIONS 

-- Q.1 Retrieve the total number of orders placed.

SELECT COUNT(ORDER_ID) AS TOTAL_ORDERS FROM ORDERS;

-- Q.2 Calculate the total revenue generated from pizza sales.

SELECT 
ROUND(SUM(orders_details.QUANTITY * PIZZAS.PRICE),2) AS TOTAL_REVENUE
FROM ORDERS_DETAILS JOIN pizzas
ON PIZZAS.PIZZA_ID = ORDERS_DETAILS.PIZZA_ID;

-- Q.3 Identify the highest-priced pizza

SELECT * FROM PIZZAS
ORDER BY PRICE DESC
LIMIT 1;

-- Q.4 Identify the most common pizza size ordered.

SELECT PIZZAS.SIZE , COUNT(ORDERS_DETAILS.ORDER_DETAILS_ID) AS ORDER_COUNT
FROM PIZZAS 
JOIN ORDERS_DETAILS
ON PIZZAS.PIZZA_ID = ORDERS_DETAILS.PIZZA_ID
GROUP BY PIZZAS.SIZE
ORDER BY ORDER_COUNT DESC;

-- Q.5 List the top 5 most ordered pizza types along with their quantities.

SELECT PIZZA_TYPES.NAME,
SUM(ORDERS_DETAILS.QUANTITY) AS QUANTITY
FROM PIZZA_TYPES JOIN PIZZAS
ON PIZZA_TYPES.PIZZA_TYPE_ID = PIZZAS.PIZZA_TYPE_ID
JOIN ORDERS_DETAILS
ON ORDERS_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID
GROUP BY PIZZA_TYPES.NAME ORDER BY QUANTITY DESC 
LIMIT 5;

-- INTERMEDIATE LEVEL QUESTIONS 

-- Q.1 Join the necessary tables to find the total quantity of each pizza category ordered.

SELECT PIZZA_TYPES.CATEGORY,
SUM(ORDERS_DETAILS.QUANTITY) AS QUANTITY
FROM PIZZA_TYPES JOIN PIZZAS
ON PIZZA_TYPES.PIZZA_TYPE_ID = PIZZAS.PIZZA_TYPE_ID
JOIN ORDERS_DETAILS
ON ORDERS_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID
GROUP BY PIZZA_TYPES.CATEGORY ORDER BY QUANTITY DESC;

-- Q.2 Determine the distribution of orders by hour of the day.

SELECT HOUR (ORDER_TIME), COUNT(ORDER_ID) FROM ORDERS
GROUP BY HOUR(ORDER_TIME);

-- Q.3 Join relevant tables to find the category-wise distribution of pizzas.

SELECT CATEGORY , COUNT(NAME) FROM PIZZA_TYPES
GROUP BY CATEGORY;

-- Q.4 Group the orders by date and calculate the average number of pizzas ordered per day.

SELECT ROUND(AVG(QUANTITY),0) FROM 
(SELECT ORDERS.ORDER_DATE, SUM(ORDERS_DETAILS.QUANTITY) AS QUANTITY 
FROM ORDERS JOIN ORDERS_DETAILS
ON ORDERS.ORDER_ID = ORDERS_DETAILS.ORDER_ID
GROUP BY ORDERS.ORDER_DATE) AS ORDER_QUANTITY;

-- Q.5 Determine the top 3 most ordered pizza types based on revenue.

SELECT PIZZA_TYPES.NAME , 
SUM(ORDERS_DETAILS.QUANTITY * PIZZAS.PRICE) AS REVENUE
FROM PIZZA_TYPES JOIN PIZZAS
ON PIZZA_TYPES.PIZZA_TYPE_ID = PIZZAS.PIZZA_TYPE_ID
JOIN ORDERS_DETAILS
ON PIZZAS.PIZZA_ID = ORDERS_DETAILS.PIZZA_ID
GROUP BY PIZZA_TYPES.NAME
ORDER BY REVENUE DESC
LIMIT 3;






